name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout changes
      uses: actions/checkout@v2

    - name: install libubox
      run: |
        git clone https://github.com/xfguo/libubox.git
        cd libubox
        cmake -DBUILD_LUA=off
        sudo make install
        
    - name: install uci
      run: |
        git clone https://github.com/jkjuopperi/uci.git
        cd uci
        cmake -DBUILD_LUA=off
        sudo make install
    
    - name: install other depend lib
      run: |
         sudo apt-get install libjson-c-dev
    
    - name: install libevent2
      run: |
        git clone https://github.com/libevent/libevent.git
        cd libevent
        git checkout tags/release-2.1.12-stable -b 2.1.12-stable
        mkdir build && cd build
        cmake ..
        make
        sudo make install
    
    - name: install iptables lib 
      run: |
        wget https://netfilter.org/projects/iptables/files/iptables-1.8.3.tar.bz2
        tar jxf iptables-1.8.3.tar.bz2
        cd iptables-1.8.3
        wget https://raw.githubusercontent.com/openwrt/openwrt/openwrt-19.07/package/network/utils/iptables/patches/101-remove-check-already.patch
        patch -p1 < 101-remove-check-already.patch
        wget https://raw.githubusercontent.com/openwrt/openwrt/openwrt-19.07/package/network/utils/iptables/patches/102-iptables-disable-modprobe.patch
        patch -p1 < 102-iptables-disable-modprobe.patch
        wget https://raw.githubusercontent.com/openwrt/openwrt/openwrt-19.07/package/network/utils/iptables/patches/103-optional-xml.patch
        patch -p1 < 103-optional-xml.patch
        wget https://raw.githubusercontent.com/openwrt/openwrt/openwrt-19.07/package/network/utils/iptables/patches/200-configurable_builtin.patch
        patch -p1 < 200-configurable_builtin.patch
        wget https://raw.githubusercontent.com/openwrt/openwrt/openwrt-19.07/package/network/utils/iptables/patches/600-shared-libext.patch
        patch -p1 < 600-shared-libext.patch
        ./configure --disable-nftables
        make
        sudo make install
           
    - name: compile apfree-wifidog
      run: |
        mkdir build
        cd build
        cmake ..
        make
    
      
