name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout changes
      uses: actions/checkout@v2

    - name: install libubox
      run: |
        git clone https://github.com/xfguo/libubox.git
        cd libubox
        cmake -DBUILD_LUA=off
        sudo make install
        
    - name: install uci
      run: |
        git clone https://github.com/jkjuopperi/uci.git
        cd uci
        cmake -DBUILD_LUA=off
        sudo make install
    
    - name: install libevent-2.1
      run: |
        sudo apt-get install openssl
        git clone https://github.com/libevent/libevent.git
        cd libevent
        git checkout tags/release-2.1.12-stable -b 2.1.12-stable
        ./configure
        make
        sudo make install
        
    - name: compile apfree-wifidog
      run: |
        mkdir build
        cd build
        cmake ..
        make
    
      
