name: compile apfree-wifidog in ubuntu system

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout changes
      uses: actions/checkout@v2

    - name: install libubox
      run: |
        git clone https://github.com/xfguo/libubox.git
        cd libubox
        cmake -DBUILD_LUA=off
        sudo make install
        
    - name: install uci
      run: |
        git clone https://github.com/jkjuopperi/uci.git
        cd uci
        cmake -DBUILD_LUA=off
        sudo make install
    
    - name: install other depend lib
      run: |
          sudo apt-get update -y
          sudo apt-get install -y libjson-c-dev
          sudo apt-get install -y libssh2-1-dev
          sudo apt-get install -y libevent-dev
    
    - name: iptables version
      run: |
        iptables -V
        which iptables
      
    - name: install iptables lib 
      run: | 
        git clone https://github.com/liudf0716/iptables-apfree-wifidog.git
        cd iptables-apfree-wifidog
        ./autogen.sh
        ./configure --disable-nftables
        make
        sudo make install
   
    - name: iptables version
      run: |
        iptables -V
        which iptables
      
    - name: compile apfree-wifidog
      run: |
        mkdir build
        cd build
        cmake ..
        make
    
      
